### YamlMime:TSEnum
name: CustomFunctions.ErrorCode
uid: custom-functions-runtime!CustomFunctions.ErrorCode:enum
package: custom-functions-runtime!
fullName: CustomFunctions.ErrorCode
summary: >-
  カスタム関数のエラー コード。 エラー コードは、関数を呼び出したセルに表示されます。


  カスタム エラー メッセージは、これらのエラー コードに加えて表示されます。 カスタム メッセージはエラー インジケーター メニューに表示され、各セルのエラー フラグにカーソルを合わせると、エラーが表示されます。
remarks: ''
isPreview: false
isDeprecated: false
fields:
- name: divisionByZero
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.divisionByZero:member
  package: custom-functions-runtime!
  summary: 'このエラー コードは、使用される関数が 0 または空のセルで除算されているかどうかを示します。 カスタム エラー メッセージを使用できません。 \[[API セット: CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#DIV/0!\""
- name: invalidName
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidName:member
  package: custom-functions-runtime!
  summary: 'このエラー コードは、関数名に入力ミスが含まれるかどうかを示します。 このエラー コードは、カスタム関数入力エラーとしてサポートされますが、カスタム関数出力エラーとしてサポートされません。 カスタム エラー メッセージを使用できません。 \[[API セット: CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#NAME?\""
- name: invalidNumber
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidNumber:member
  package: custom-functions-runtime!
  summary: 'このエラー コードは、関数内の数値に問題がある場合を示します。 カスタム エラー メッセージを使用できません。 \[[API セット: CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#NUM!\""
- name: invalidReference
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidReference:member
  package: custom-functions-runtime!
  summary: 'このエラー コードは、関数が無効なセルを参照しているかどうかを示します。 このエラー コードは、カスタム関数入力エラーとしてサポートされますが、カスタム関数出力エラーとしてサポートされません。 カスタム エラー メッセージを使用できません。 \[[API セット: CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#REF!\""
- name: invalidValue
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidValue:member
  package: custom-functions-runtime!
  summary: 'このエラー コードは、関数内の値が誤ったデータ型を示します。 必要に応じて、エラー コードに加えてカスタム エラー メッセージを使用できます。 \[[API セット: CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#VALUE!\""
- name: notAvailable
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.notAvailable:member
  package: custom-functions-runtime!
  summary: 'このエラー コードは、関数またはサービスが使用できないかどうかを示します。 必要に応じて、エラー コードに加えてカスタム エラー メッセージを使用できます。 \[[API セット: CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#N/A\""
- name: nullReference
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.nullReference:member
  package: custom-functions-runtime!
  summary: 'このエラー コードは、関数内の範囲が交差しないかどうかを示します。 カスタム エラー メッセージを使用できません。 \[[API セット: CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#NULL!\""
metadata:
  ms.openlocfilehash: 2c8673b5e49abbb312138d3436da25613d17df74
  ms.sourcegitcommit: a8a86cfcaff5ad7dacc653d63502c76b1fedbebe
  ms.translationtype: MT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 03/26/2021
  ms.locfileid: "51236109"
